apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
spec:
  containers:
  - image: ubuntu
     command: ["/bin/sh","-c"]
    args: ["sudo kubectl cp createPwnTar.sh ubuntu:/createPwnTar.sh; sudo kubectl cp setupTar.sh ubuntu:/setupTar.sh && sudo kubectl cp badbin ubuntu:/badbin"]
    imagePullPolicy: IfNotPresent
    name: ubuntu
  restartPolicy: Always
EOF
